package com.technology.jep.jepriashowcase.requestfeature.client;

public class RequestFeatureAutomationConstant {
	/**
	 * Идентификаторы полей детальной формы
	 */
	public static final String REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_FROMDATEINS_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_FROMDATEINS_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_TODATEINS_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_TODATEINS_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_ROWCOUNT_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_ROWCOUNT_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD_INPUT_ID = "REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD_INPUT_ID";
	
}
