package com.technology.jep.jepriashowcase.requestfeature.client;

public class RequestFeatureAutomationConstant {
	/**
	 * Идентификаторы полей детальной формы
	 */
	public static final String REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD_ID_INPUT = "REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD_INPUT";
	public static final String REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD_ID_INPUT = "REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD_INPUT";
	public static final String REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID_INPUT = "REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD_INPUT";
	public static final String REQUESTFEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID_INPUT = "REQUESTFEATURE_MAXROWCOUNT_DETAILFORM_FIELD_INPUT";
	public static final String REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD_ID_INPUT = "REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD_INPUT";
	
	public static final String REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD_ID = "REQUESTFEATURE_FEATUREID_DETAILFORM_FIELD";
	public static final String REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD_ID = "REQUESTFEATURE_FEATURENAME_DETAILFORM_FIELD";
	public static final String REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID = "REQUESTFEATURE_FEATURENAMEEN_DETAILFORM_FIELD";
	public static final String REQUESTFEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID = "REQUESTFEATURE_MAXROWCOUNT_DETAILFORM_FIELD";
	public static final String REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD_ID = "REQUESTFEATURE_DESCRIPTION_DETAILFORM_FIELD";
	
}
