package com.technology.jep.jepriashowcase.featurerequest.client;

public class FeatureRequestAutomationConstant {
	/**
	 * Идентификаторы полей детальной формы
	 */
	public static final String FEATUREREQUEST_FEATUREID_DETAILFORM_FIELD_ID_INPUT = "FEATUREREQUEST_FEATUREID_DETAILFORM_FIELD_INPUT";
	public static final String FEATUREREQUEST_FEATURENAME_DETAILFORM_FIELD_ID_INPUT = "FEATUREREQUEST_FEATURENAME_DETAILFORM_FIELD_INPUT";
	public static final String FEATUREREQUEST_FEATURENAMEEN_DETAILFORM_FIELD_ID_INPUT = "FEATUREREQUEST_FEATURENAMEEN_DETAILFORM_FIELD_INPUT";
	public static final String FEATUREREQUEST_MAXROWCOUNT_DETAILFORM_FIELD_ID_INPUT = "FEATUREREQUEST_MAXROWCOUNT_DETAILFORM_FIELD_INPUT";
	public static final String FEATUREREQUEST_DESCRIPTION_DETAILFORM_FIELD_ID_INPUT = "FEATUREREQUEST_DESCRIPTION_DETAILFORM_FIELD_INPUT";
	
	public static final String FEATUREREQUEST_FEATUREID_DETAILFORM_FIELD_ID = "FEATUREREQUEST_FEATUREID_DETAILFORM_FIELD";
	public static final String FEATUREREQUEST_FEATURENAME_DETAILFORM_FIELD_ID = "FEATUREREQUEST_FEATURENAME_DETAILFORM_FIELD";
	public static final String FEATUREREQUEST_FEATURENAMEEN_DETAILFORM_FIELD_ID = "FEATUREREQUEST_FEATURENAMEEN_DETAILFORM_FIELD";
	public static final String FEATUREREQUEST_MAXROWCOUNT_DETAILFORM_FIELD_ID = "FEATUREREQUEST_MAXROWCOUNT_DETAILFORM_FIELD";
	public static final String FEATUREREQUEST_DESCRIPTION_DETAILFORM_FIELD_ID = "FEATUREREQUEST_DESCRIPTION_DETAILFORM_FIELD";
	
}
