package com.technology.jep.jepriashowcase.requestfunct.client;

public class RequestFunctAutomationConstant {
	/**
	 * Идентификаторы полей детальной формы
	 */
	public static final String REQUESTFUNCT_FEATUREID_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_FEATUREID_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_FEATURENAME_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_FEATURENAME_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_FEATURENAMEEN_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_FEATURENAMEEN_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_FROMDATEINS_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_FROMDATEINS_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_TODATEINS_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_TODATEINS_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_ROWCOUNT_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_ROWCOUNT_DETAILFORM_FIELD_INPUT_ID";
	public static final String REQUESTFUNCT_DESCRIPTION_DETAILFORM_FIELD_INPUT_ID = "REQUESTFUNCT_DESCRIPTION_DETAILFORM_FIELD_INPUT_ID";
	
}
