package com.technology.jep.jepriashowcase.feature.client;

public class FeatureAutomationConstant {
  /**
   * Идентификаторы полей детальной формы
   */
  public static final String FEATURE_FEATUREID_DETAILFORM_FIELD_ID = "FEATURE_FEATUREID_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURENAME_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAME_DETAILFORM_FIELD";
  public static final String FEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAMEEN_DETAILFORM_FIELD";
  public static final String FEATURE_FROMDATEINS_DETAILFORM_FIELD_ID = "FEATURE_FROMDATEINS_DETAILFORM_FIELD";
  public static final String FEATURE_TODATEINS_DETAILFORM_FIELD_ID = "FEATURE_TODATEINS_DETAILFORM_FIELD";
  public static final String FEATURE_DESCRIPTION_DETAILFORM_FIELD_ID = "FEATURE_DESCRIPTION_DETAILFORM_FIELD";
  public static final String FEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID = "FEATURE_MAXROWCOUNT_DETAILFORM_FIELD";
  
}
