package com.technology.jep.jepriashowcase.feature.client;

public class FeatureAutomationConstant {
	/**
	 * Идентификаторы полей детальной формы
	 */
	public static final String FEATURE_FEATUREID_DETAILFORM_FIELD_ID_INPUT = "FEATURE_FEATUREID_DETAILFORM_FIELD_INPUT";
	public static final String FEATURE_FEATURENAME_DETAILFORM_FIELD_ID_INPUT = "FEATURE_FEATURENAME_DETAILFORM_FIELD_INPUT";
	public static final String FEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID_INPUT = "FEATURE_FEATURENAMEEN_DETAILFORM_FIELD_INPUT";
	public static final String FEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID_INPUT = "FEATURE_MAXROWCOUNT_DETAILFORM_FIELD_INPUT";
	
	public static final String FEATURE_FEATUREID_DETAILFORM_FIELD_ID = "FEATURE_FEATUREID_DETAILFORM_FIELD";
	public static final String FEATURE_FEATURENAME_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAME_DETAILFORM_FIELD";
	public static final String FEATURE_FEATURENAMEEN_DETAILFORM_FIELD_ID = "FEATURE_FEATURENAMEEN_DETAILFORM_FIELD";
	public static final String FEATURE_MAXROWCOUNT_DETAILFORM_FIELD_ID = "FEATURE_MAXROWCOUNT_DETAILFORM_FIELD";
	
}
