package com.technology.jep.jepriashowcase.arsenic.client;


public class ArsenicAutomationConstant {
	public static final String ARSENIC_JEP_TEXT_FIELD_ID = "ARSENIC_JEP_TEXT_FIELD";
	public static final String ARSENIC_JEP_TEXT_AREA_FIELD_ID = "ARSENIC_JEP_TEXT_AREA_FIELD";
	public static final String ARSENIC_JEP_INTEGER_FIELD_ID = "ARSENIC_JEP_INTEGER_FIELD";
	public static final String ARSENIC_JEP_LONG_FIELD_ID = "ARSENIC_JEP_LONG_FIELD";
	public static final String ARSENIC_JEP_MONEY_FIELD_ID = "ARSENIC_JEP_MONEY_FIELD";
	public static final String ARSENIC_JEP_NUMBER_FIELD_ID = "ARSENIC_JEP_NUMBER_FIELD";
	public static final String ARSENIC_JEP_DATE_FIELD_ID = "ARSENIC_JEP_DATE_FIELD";
	
	public static final String ARSENIC_JEP_COMBOBOX_FIELD_NOTLAZY_ID = "ARSENIC_JEP_COMBOBOX_FIELD_NOTLAZY";
	public static final String ARSENIC_JEP_COMBOBOX_FIELD_SIMPLE_ID = "ARSENIC_JEP_COMBOBOX_FIELD_SIMPLE";
	public static final String ARSENIC_JEP_COMBOBOX_FIELD_DURABLE_ID = "ARSENIC_JEP_COMBOBOX_FIELD_DURABLE";
	public static final String ARSENIC_JEP_COMBOBOX_FIELD_RELOADING_ID = "ARSENIC_JEP_COMBOBOX_FIELD_RELOADING";
	public static final String ARSENIC_JEP_COMBOBOX_FIELD_3CH_RELOADING_ID = "ARSENIC_JEP_COMBOBOX_FIELD_3CH_RELOADING";
	
	public static final String ARSENIC_JEP_DUAL_LIST_FIELD_ID = "ARSENIC_JEP_DUAL_LIST_FIELD";
	public static final String ARSENIC_JEP_CHECKBOX_FIELD_ID = "ARSENIC_JEP_CHECKBOX_FIELD";
	public static final String ARSENIC_JEP_LIST_FIELD_ID = "ARSENIC_JEP_LIST_FIELD";
}
